### ISSUE TITLE
Error while saving a file

### ISSUE THREAD

**Issue by butterknight** [zabel-xyz/local-history#1]
Greetings. First of all, let me say that I love the extension! it's the kind of thing I most looked forward to when they announced the addition of the plugin system for VSCode. Coming from NetBeans, a good local history system is very dear to me.

However, I do have a bit of an issue with the extension.

I had a running project and I installed the extension, restarted, and every time I try to save a file I get an error like the following (the 'blah blah' thing is a path to the project and it's long so I shortened it for easier reading):
Can not save the revision of the file: [BLAH_BLAH]/app/tags/content.tag Error: Error: ENOENT: no such file or directory, open '[BLAH_BLAH]/.history/app/tags/content_20160115205539.tag'

Note that when I checked the location, there were no files there, not even a .history folder.

If I create a new file, however, it works flawlessly, but every time I try to save an existing file, I get an error like that.

**Comment by zabel-xyz** [comment]
Nice that you like this extension ! I'm sorry that you encounter an issue.
In version 0.0.3 I use mkdirp to create history structure, I hope this will resolve your issue...

**Comment by butterknight** [comment]
Seems to be working now. Wonderful, thanks!
