### ISSUE TITLE
how to revert delete files?

### ISSUE THREAD

**Issue by ychab** [zabel-xyz/local-history#10]
I didn't found how... Of course, I found deleted files in the ``.history`` directory but there is a way to do it with GUI?

BTW : we could only see changes (i.e : we cannot revert some parts of the diff when comparing two versions)?

Thanks

**Comment by zabel-xyz** [comment]
Currently there isn't other way to delete files. In the future, I'll add some commands to delete files or purge folders, because .history path can now be setting externally (see issue #11).

I'm not sure what you mean by "_cannot revert some parts of the diff_ ". The comparison is vscode functionality, the left part is always in read only mode...

**Comment by ychab** [comment]
> Currently there isn't other way to delete files. In the future, I'll add some commands to delete files or purge folders, because .history path can now be setting externally (see issue #11).

Not sure we are talking about the same thing... :/ My question was how to revert deleted file in the GUI? Fortunetly, I can found deleted files (accidently) in the default location ``.history`` (which is just fine for me, so I don't override the setting!) and pick them manually!

> I'm not sure what you mean by "cannot revert some parts of the diff ". The comparison is vscode functionality, the left part is always in read only mode...

Oh I see, I wasn't sure. Yes, that's exactly what I'm talking about. When you are comparing two versions, being able to click on a diff to revert it.
I suppose it use the same component of the git diff feature (or something else) which doesn't implement this.

Anyway, thank you for this feature which already save me! Yeah, even with Git, we could do some mistake ;-)
