### ISSUE TITLE
Default to not storing .history in the workspace

### ISSUE THREAD

**Issue by vvo** [zabel-xyz/local-history#101]
Creating .history in the project workspace triggers different kind of issues (searching, git ignore, linting tools), could we store .history folder globally in ~/.vscode-local-history or something?

Can this be configured? I could not find the right way/example to do it.

Thanks @zabel-xyz, your plugin rocks, this should be a default feature of vscode.

**Comment by zabel-xyz** [comment]
See #47 and #43 
Warning: character ~ is supported for save only (version 1.8.0). 
There are still some failure (restore...) I'm working to improve this...
