### ISSUE TITLE
Add delete and purge commands

### ISSUE THREAD

**Issue by zabel-xyz** [zabel-xyz/local-history#11]
To improve delete or purge ways, add some commands.
(.history path can now be external to workspace )

- Purge history for current file (before a date ?)
- Purge history for current workspace (before a date ?)
- Delete an history file 
- Add this commands also in html view

**Comment by zabel-xyz** [comment]
How to revert delete files?
Duplicate of #23

Other features for deletion are already implemented...

**Comment by MarekLew** [comment]
You must  show forders tree view where show last changet files state, only changet or deleted files, other files is "hidden". From this view menu items go to show file history or replace last state.
