### ISSUE TITLE
Local History fails on Win-SSHFS-mounted (or SFTP) workspace

### ISSUE THREAD

**Issue by anttin2020** [zabel-xyz/local-history#115]
Hi!

I use Win-SSHFS to mount remote workspace (Remote Development extension is resource hog, I cannot use it on a webhotel).
The permissions are correct on the linux side and as long as I create files/folders on my own or directly in VSCode UI, everything works.

VSCode process is owned by me and my account belongs to Administrators:

BUT when VSCode extension Local History tries to write files for the first time, it creates subfolder .history and then writes the first history file there. It works ONCE for each folder i.e. when the folder does not already exist but still it gives the error:
`Error with mkdir: 'Error: EPERM: operation not permitted, mkdir 'n:\public_html\.history'' file 'n:\public_html\.history\index_20200622181510.html`
Same happens for any subdirs in that history folder but only succeeds when the directory does not already exist.
To me it seems that for some reason, creating file in existing directory fails but only on SSHFS, not locally. If the directory is created when creating a file in there, it works. It looks like Local History always tries to create the folders on the path regardless if they already exist. That seems to work in Windows locally but something goes wrong on remote files.

Any ideas or is Local History just incompatible with SSHFS/SFTP?

Thank you very much!

Antti

**Comment by anttin2020** [comment]
The same happens when using SFTPDrive so the problem is not in SSHFS.
It works fine when I set the history root to local folder but of course it should also work on the remote.

**Comment by allenyllee** [comment]
I have the same issue too....
