### ISSUE TITLE
Integration with VSHistory

### ISSUE THREAD

**Issue by NN---** [zabel-xyz/local-history#124]
It would be nice to use VSHistory files too: https://marketplace.visualstudio.com/items?itemName=KenCross.VSHistory

**Comment by zabel-xyz** [comment]
It's a visual studio extension, not a visual studio code !
It's not the same...

**Comment by NN---** [comment]
I know.
It could be nice if opening a file in VSCode could also show saved history of such file changed in VS.

**Comment by zabel-xyz** [comment]
But I can't access vs extension configuration !
