### ISSUE TITLE
Visual Studio Code projects with csproj extension can cause problems

### ISSUE THREAD

**Issue by pabloarista** [zabel-xyz/local-history#13]
This extension causes problem for me when working on C# projects. Problem is that if there is a project that has a csproj file, then there is problems with the history folder.
I'm not sure if it's possible to add an exclude or maybe add this just to the description that if you don't exclude .history (or the custom location), then if you're using the C# extension the omnisharp daemon will go crazy and sometimes making the CPU max out and making the reference not working or delaying. When I added a "files.exclude" for the .history, it went away and everything works great for my C# projects. Maybe the best solution is just to inform users in the description, but if it is possible to exclude it by default, then that would work too. If anything anyone coming here can see my solution. At the very least I hope this helps someone having the same issue as me. The problem wasn't so bad, but when .NET core updated to using csproj files, then the problems got worst as all of my projects got issues.

**Comment by zabel-xyz** [comment]
This is the right solution to add a "files.exclude" for the .history in this case.
Alternatively, you can use an external path to save the history (external to the workspace)

I don't want to hide the .history folder automatically, as it may be useful to access this folder directly in vscode (when there isn't any issue).
However, I will add a note in readme to prevent someone from encountering such a problem.

**Comment by pabloarista** [comment]
Great!

**Comment by parthvora25** [comment]
How to hide the .history folder from the workspace. I mean to ask what to add in settings.json file to hide it
