### ISSUE TITLE
File history is being saved but not read

### ISSUE THREAD

**Issue by EJLearner** [zabel-xyz/local-history#14]
Everything is saving to the folder as it should but when I use any of the commands inside of VSC, I either get a "No history" window or I get no noticeable action at all. It seems that the plugin is correctly writing the files but not seeing them after they're written.

**Comment by lqygo123** [comment]
i have this problem too, just the first time the local history works, then it's always "No history"

**Comment by zabel-xyz** [comment]
Hi,

I haven't such an issue...

How is your setting ? Do you use local-history.path ? 
What system do you use ? (I only can test on Windows 10)
Have you try to disable all extensions ?

**Comment by EJLearner** [comment]
It is on Windows 10. I have to wait until I'm back at my computer to answer
the rest of the questions and try disabling other extension. I should be
able to answer with more details tomorrow at the latest. Thanks for looking
into it.

**Comment by EJLearner** [comment]
I left local-history path as default and I'm on Windows 10. The only other extensions I have installed are PHP Intellisense and Auto Close Tag. I disabled them but I still had the same issue.

I actually just set the local-history path to something else and things seem to be working correctly.

Is there a known issue when the local-history path is left as default?

**Comment by zabel-xyz** [comment]
The default for local-history.path is ${workspaceRoot}. It's s what I use daily without any problem.
I don't know what could be the cause of this issue...

**Comment by EJLearner** [comment]
Ok, I think that I'm doing something wrong here, then.

If I don't put any value for local-history.path (not listed in user settings at all), the files save but aren't seen when I use the local history commands

Using "${workspaceRoot}" as the setting gives me an error and it appears that vscode isn't resolving the variable correctly.

![image](https://cloud.githubusercontent.com/assets/22520333/26082454/1124d07a-399e-11e7-821a-1cdbd9a3fe69.png)

The only thing that's working for me is using a path directly.

Can answer more questions if you have any...just takes a while for me to get a chance to respond.

**Comment by zabel-xyz** [comment]
You cannot use the "$ {workspaceRoot}" variable, but this is what is supposed to be used when you do not set any values for the local history path.
I will improve the html output to indicate the path when no history is found. Maybe this will give us a track to find out what's going wrong ...

**Comment by zabel-xyz** [comment]
In version 1.2.1, settings are displayed event if there is no history
