### ISSUE TITLE
Saving to `%AppData%\Code`

### ISSUE THREAD

**Issue by borekb** [zabel-xyz/local-history#15]
I'd like to save to `%AppData%\Code` but with this line in my user settings.json:

```
"local-history.path": "%AppData%\\Code"
```

I get an error creating directory or something. It seems that it tries to append `%AppData%\\Code` to the current working directory instead of resolving it to a full path.

Awesome extension btw :)

**Comment by zabel-xyz** [comment]
The path with %[Windows variables]% are not suported yet.

**Comment by zabel-xyz** [comment]
fix in version 1.2.1

**Comment by borekb** [comment]
Very cool, thank you!
