### ISSUE TITLE
Save full path to edited file

### ISSUE THREAD

**Issue by ataran17** [zabel-xyz/local-history#16]
Hello.
Currently "local-history.path" parameter changes where extention saves edited file with relative path to opened workspace. That's fine but not always.

i.e. 
- set "local-history.path": "c:\\history\"
- if we open c:\projects directory.
- edit file .\hello-world\file.txt
then history file will be saved to c:\history\.history\projects\hello-world\.

What if I open the same project from different paths (like current and archive/backup).
History will be messed up.

It would be more consistent if extention saves full path (from root directory inside .history) to file, so that one can find for sure where edited file exists.
like this: c:\history\.history\c\projects\hello-world\file-yyyymmddhhmiss3.
like this: c:\history\.history\d\projects\hello-world\.

The same way works SublimeText and Atom.

Thank you, Alexander.

**Comment by zabel-xyz** [comment]
I had already thought of this alternative. Especially to save a file history when no workspace is loaded (issue 8).
I started something for this purpose, I'll publish it soon ...

**Comment by zabel-xyz** [comment]
Fix in version 1.3.0
Set new settings 'absolute'  to true.
