### ISSUE TITLE
Delay on save

### ISSUE THREAD

**Issue by Sethios** [zabel-xyz/local-history#20]
If auto-save is enabled or you save often, it generated too many history files for only small changes.

Some cooldown timer / delay on history generation would be a great option to have, like:
- create a new history file if the last one is older then 5 minutes

**Comment by zabel-xyz** [comment]
Why not... Good idea...

**Comment by zabel-xyz** [comment]
Fix in version 1.16.0

I added a settings **local-history.saveDelay** to specify the delay in seconds after which local-history is saved and so avoid too many history files.
