### ISSUE TITLE
save/load history where file open  from command line

### ISSUE THREAD

**Issue by MarekLew** [zabel-xyz/local-history#24]
When file is open from the  command line "code -r {path to file}" then history not saved and not loaded, 
even if the file is in the current directory. I must close file and reopen from explorer panel (VSC), then history loaded and created. 

extension: 1.6.0
vsc: 1.17.1
system: windows 10 Home 10  version 10.0.15063 compile 15063

The bug start exist befor 1.6.0, 1.5.2 mayby or in vsc 1.17 (I do not know when).

**Comment by MarekLew** [comment]
It's VSC bug `vscode.workspace.getWorkspaceFolder(file)` don't return workspace folder when file open from command line. https://github.com/Microsoft/vscode/issues/36221

**Comment by MarekLew** [comment]
It's VSC bug `vscode.workspace.getWorkspaceFolder(file)` don't return workspace folder when file open from command line. https://github.com/Microsoft/vscode/issues/36221

**Comment by zabel-xyz** [comment]
I noticed this bug, but haven't tell this to vscode yet.
Thank you for the bug report to vscode team...

**Comment by MarekLew** [comment]
You have commentet block in `HistorySettings.get`(file history.settings.ts) when I uncoment and modyfi

```
        if (!folder){
            folder = vscode.workspace.rootPath ? vscode.Uri.file(vscode.workspace.rootPath) : undefined;
            if (folder) {
                // if file is not a child of workspace => undefined
                const relativeFile = vscode.workspace.asRelativePath(file.fsPath);
                if (relativeFile === file.fsPath.replace(/\\/g, '/'))
                    folder = undefined;
            }
        }
```

then at this moment work fine.

**Comment by zabel-xyz** [comment]
I commented this code because vscode.workspace.rootPath is now deprecated, according to https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs
I think is a bug in Multi Root Workspace APIs....

**Comment by MarekLew** [comment]
It's propably don't fixed before vcs 1.18.0 becaus do not exist in 1.18.0-insider Version.

**Comment by MarekLew** [comment]
`vscode.workspace.getWorkspaceFolder(file)` it`s not stable.  Use `workspaceFolders[i]` as rootPath.

**Comment by zabel-xyz** [comment]
I'll publish a version with this fix (this will resolve this issue, waiting version 1.18.0)

  ```
      let folder;
        const wsFolder = vscode.workspace.getWorkspaceFolder(file);
        if (wsFolder)
            folder = wsFolder.uri;
        // temporary code to resolve bug https://github.com/Microsoft/vscode/issues/36221
        else if (file && vscode.workspace.workspaceFolders && vscode.workspace.workspaceFolders.length === 1) {
            if (file.fsPath.includes(vscode.workspace.workspaceFolders[0].uri.fsPath))
                folder = vscode.workspace.workspaceFolders[0].uri;
        }
```

**Comment by zabel-xyz** [comment]
Publish a temporary workaround  in version 1.6.1
