### ISSUE TITLE
Availability for VS Professional

### ISSUE THREAD

**Issue by rok7** [zabel-xyz/local-history#25]
Could yo please make this tool also available on the marketplace of Visual Studio? I'm missing the local file history a lot in VS 2017 Professional. 
Thank you!

**Comment by zabel-xyz** [comment]
Sorry, but it's not possible !
VSCode is not the same product than Visual Studio 2017 and extensions are not compatible.
Perhaps an extension for VS 2017 like that already exists , but I don't know because I don't use VS 2017.
