### ISSUE TITLE
Show file version's age in .history

### ISSUE THREAD

**Issue by ecerroni** [zabel-xyz/local-history#27]
This extension is already awesome though besides name + date it'd be useful to have also version's age like:
- moments ago
- few minutes ago
- 15 minutes ago
- 1 hour ago
- yesterday
- last week

Something among these lines.

**Comment by zabel-xyz** [comment]
What exactly do you want ? 
In tree explorer the history is already grouped by relative date (last hour, today, yesterday...)

In html or command view, this is not the case.  If someone has some interest in, I'll improve this views too. (Personnaly I don't use them anymore...)
