### ISSUE TITLE
Add option to disable when using a git repository

### ISSUE THREAD

**Issue by bengry** [zabel-xyz/local-history#28]
When I'm already in a git repository, I'm less likely to need the `local-history` plugin.

I suggest adding a `4` option to the `"local-history.enabled"`.

**Comment by carlos-algms** [comment]
-1
Use local history is an addiction to git, not a competition, it is great to have versioning even without commit the file. 

Intellij, webStorm and all brainStorm IDEs have this enabled by default and I'm pretty sure that there is no way to disable it.

**Comment by zabel-xyz** [comment]
I agree with @carlos-algms, it can be usefull to have versioning and git working together. 
I'll not implement such a feature..
