### ISSUE TITLE
Ignoring .history direction for syntax check etc.

### ISSUE THREAD

**Issue by mfour-merickson** [zabel-xyz/local-history#29]
Plugin is working great, just curious if there is some way to "hide" the .history directory from linting tools (ESLint and PHP CS Fixer) All the files listed in screenshot below are files from `.history` directory (with the exception of one)

![image](https://user-images.githubusercontent.com/31225533/33443607-e2adaf04-d5ac-11e7-9eeb-e1ad5aac22b4.png)

**Comment by zabel-xyz** [comment]
I don't know if these tools consider settings **search.exclude**
```
	"search.exclude": {
		"**/node_modules": true,
		"**/bower_components": true,
                 "**/.history": true
	},
```
or maybe **files.exclude**
```
  "files.exclude": {
    "**/.git": true,
    "**/.svn": true,
    "**/.hg": true,
    "**/CVS": true,
    "**/.DS_Store": true,
    "**/.history": true
  },
```

**Comment by mfour-merickson** [comment]
@zabel-xyz Ahhh, I see what you are saying.  There is really no way for you to control their extensions :-)  But I do appreciate the feedback, I will track this down!
