### ISSUE TITLE
Move the .history folder to .vscode folder since it is already ignored by some repositories

### ISSUE THREAD

**Issue by carlos-algms** [zabel-xyz/local-history#30]
It will be great if we would not need to add a new record to .gitignore file.

Most of the projects already ignore the IDEs folders, and ignore a new folder will impact the other team members that are unaware.

**Comment by zabel-xyz** [comment]
I think, this is resolved by issue #26

**Comment by carlos-algms** [comment]
Yeah it is fixed, thanks. but it would be great if `.vscode/.history` were the default folder since a lot of projects already ignore the `.vscode` folder. 

**You can close if you want to**, use the config you mentioned is working for me.
