### ISSUE TITLE
Create history only if the file changes

### ISSUE THREAD

**Issue by carlos-algms** [zabel-xyz/local-history#32]
VScode seems to trigger the save action even if the file don't have any changes.

Add a way to verify if the file is changed before create a new item on the local history will help to decrease the number of local history items stored.

**Comment by zabel-xyz** [comment]
Via ctrl+s or auto-save, it seems that VScode don't trigger anymore the save action if the file don't change...
Can you confirm ?

**Comment by carlos-algms** [comment]
You are right. Thanks!
