### ISSUE TITLE
How do I display the local-history tree?

### ISSUE THREAD

**Issue by chookie** [zabel-xyz/local-history#34]
I cannot see it in my explorer view.  I take it that it should show under open editors etc?
![image](https://user-images.githubusercontent.com/4765327/36099848-04eaadae-0ffc-11e8-90fd-0aa85d789980.png)

**Comment by zabel-xyz** [comment]
It's exactly where the local-hsitory tree will appear when you install this extension.
Perhaps it's hidden - right-click on explorer to see the list of all tree.
![image](https://user-images.githubusercontent.com/16486407/38138297-77625236-342a-11e8-814e-c3ad796551d0.png)
