### ISSUE TITLE
Saving the temp files outside the workspace?

### ISSUE THREAD

**Issue by Eksrow** [zabel-xyz/local-history#4]
Would it be possible to keep them out of the workspace(somewhere in appdata perhaps?)
Sometimes tools that watch the workspace tend to take additional unwanted actions when files change or get added and some of these don't have ignore lists. It might also seem cleaner as these files don't technically effect the workspace.

I appreciate the work on the extension so far, thank you!

**Comment by zabel-xyz** [comment]
I'll add a setting to specify the location of .history folder.
Thanks to apreciate this extension
Zabel

**Comment by Eksrow** [comment]
Thank you!

**Comment by beeman** [comment]
I second this, it would be great if this history could be saved in a central place. I was thinking about for instance saving it in the root of my home directory, for example `~/.vs-code-history/<project-name>`. 

If you can give me some guidance on how you'd like to see this implemented I might be able to have a look at it this weekend.

Great extension!

**Comment by zabel-xyz** [comment]
I am working on this feature and changed a lot of code to implements this. 
I am testing now and will publish a new version of this extension soon...
Z'abel

**Comment by zabel-xyz** [comment]
I have just published a new version of this extension. 
I added a new setting "local-history.path" to specify the .history folder location.

Z'abel

**Comment by Eksrow** [comment]
Thank you!!!

**Comment by MarekLew** [comment]
Do you add `{"local-history.folderName":".history"}` ? If I have "subproject" then this is usetfule.

**Comment by zabel-xyz** [comment]
I don't understand what do you want/need...
An exemple of folder structure would be perhaps more explicit - just sketch it out in a comment here...

Currently there is a settings "local-history.path" to specify the ".history" folder location.
    <local-history.path>\.history\workspace1
    <local-history.path>\.history\workspace1\SubFolder1
    <local-history.path>\.history\workspace2

**Comment by MarekLew** [comment]
I need change _.history_ folder name, not only _.history_ folder location.

**Comment by zabel-xyz** [comment]
I see, you need an _.history_ folder name different for each workspace.
Create a new issue for this feature or make a PR...

**Comment by ianwalter** [comment]
@zabel-xyz What about making `.vscode` or a directory inside of `.vscode` as the default directory instead of `.history` since it is already being used for project-related VS Code settings? I think this would cut down the amount of stuff users have to configure to be ignored.

**Comment by zabel-xyz** [comment]
You can already configure .history to be a subfolder of ..vscode. (See issue #30 and #26)
local-history.path: ${workspaceFolder}.vscode => .vscode\.history

**Comment by ianwalter** [comment]
@zabel-xyz Sure, but my suggestion was why not make that the default? It looks like this was also suggested in #30 but there was no response.

**Comment by f3ist** [comment]
It would be nice is there was a `{workspaceName}`. I would like to be able to save my project in my workspaces parent folder, but the parent folder has several workspace child folders in it. My ideal structure:
```
- parent-folder
  - .vscode
    - workspace 1
      - .history
    - workspace 2
      - .history
  - workspace 1
  - workspace 2
  - workspace n
```

Side note: The `window.title` setting has some variable support, that maybe this project should match (Ex: rootName & rootPath).
