### ISSUE TITLE
Add local history as activity bar item instead of panel in explorer item

### ISSUE THREAD

**Issue by PixelT** [zabel-xyz/local-history#41]
More details about this:
https://code.visualstudio.com/updates/v1_23#_extension-authoring

**Comment by zabel-xyz** [comment]
I also thought about that...

**Comment by PixelT** [comment]
This should be helped:
https://github.com/patrys/vscode-code-outline/issues/117#issuecomment-386852209

**Comment by zabel-xyz** [comment]
I you want, you can do a PR. 
(I have not enough time now to do this.)

**Comment by zabel-xyz** [comment]
In version 1.7.0, a dedicated activity bar is created according to a new setting:
```
"local-history.treeLocation": // Specify a location for tree view
        explorer (default): // Show tree in Explorer item
        localHistory:       // Show tree in a special active bar item
```

**Comment by PixelT** [comment]
![](https://i.imgur.com/Yhc7llc.png)

I think the `Local history` icon is too big when you compare it with other icons

**Comment by zabel-xyz** [comment]
Local history and Debug are the same size...(I use the vscode api description size)
![debug](https://user-images.githubusercontent.com/16486407/42799862-bd4e26a2-8999-11e8-9761-b4d1c7dea5e8.png)
![localhistory](https://user-images.githubusercontent.com/16486407/42799863-bd73f4a4-8999-11e8-8ea8-88ddeaca5664.png)

**Comment by PixelT** [comment]
You're right, sorry :)
