### ISSUE TITLE
cpu use up to 100% after saving a file

### ISSUE THREAD

**Issue by bestv2** [zabel-xyz/local-history#49]
VSCode Version: 1.25.1
OS Version: Mac OS 10.13.5
LocalHistory Version: 1.7.0
Steps to Reproduce:

open a js file.
change something, and save
outline is loading..... and code cannot be folded until outline view is ready (nothing happends when click -/+. Sometimes, the fold symbols( -, +) disappear, and when outline view is ready, they will be back.
It seems to be ok after disable the local-history extension
[https://github.com/Microsoft/vscode/issues/54449](https://github.com/Microsoft/vscode/issues/54449)

**Comment by qdechochen** [comment]
But i didn't install this extension, and the problem persists when all extensions are disabled.

Unfortunately, my post about this is closed. :(

**Comment by zabel-xyz** [comment]
So what,, @bestv2 says it's caused by localHistory extension. @qdechochen says **no I didn't install this extension** and open a new issue for the vscode team. https://github.com/Microsoft/vscode/issues/54523
I personaly not have such a problem, but I can't test on mac system...

**Comment by bestv2** [comment]
Maybe this relate to  the [file watcher but](https://github.com/Microsoft/vscode/issues/3998)

**Comment by qdechochen** [comment]
For me, it seems not be the reason. node_modules folder is excluded, and i only have 9 .js files in the workbench.
