### ISSUE TITLE
no history is saved

### ISSUE THREAD

**Issue by westr029** [zabel-xyz/local-history#52]
The local-history extension should be pretty useful for me. However, after installation it does not work.

So I have the latest VSCode update (1.26.1) on Ubuntu 16.04. Local-history is in version 1.7.0 and does show up in the explorer pane. I just use all the default settings.

I am currently working on a LaTeX document which I would like to have saved every now and then. The thing is that while writing there is no local copy / history saved. Furthermore, I could not find any error message in the Extension output panel or anything similar.

Do you have any idea on what could be the problem? Let me know if you need any extra information.

**Comment by zabel-xyz** [comment]
I test with my VM on Unbuntu 16.4, and no special settings, It works fine.

I don't know what goes wrong...! Have you try without any other extension ?
