### ISSUE TITLE
Side panel icon blurred and wrong size

### ISSUE THREAD

**Issue by lllopo** [zabel-xyz/local-history#57]
When local history is set to reside in its own panel, the icon is blurred and and bigger the the default VS Code panel icons :

![annotation](https://user-images.githubusercontent.com/5485902/47550770-ec2ae500-d908-11e8-94dc-514083651364.png)

Remark : I"m using a windows set to run on 125% display scaling, if that matters somehow.

**Comment by lllopo** [comment]
Checked the size, looks ok. The blurriness comes from the fact that the image is PNG, instead of SVG, so I'd rather recommend you to switch to SVG. Also, although the size is ok, the image looks somewhat unbalanced compared to other icons. I guess it is because of the thickness of the arrow, I tried this one :
https://www.onlinewebfonts.com/icon/72594
and I think it looks better.

**Comment by lllopo** [comment]
Same goes for the panel icons, btw - they should be SVG to avoid blurring (and a bit smaller)

**Comment by zabel-xyz** [comment]
see PR #48

**Comment by zabel-xyz** [comment]
Version 1.8.0
