### ISSUE TITLE
The extension not working with the current latest version of VSCode 1.7.1

### ISSUE THREAD

**Issue by mysticman** [zabel-xyz/local-history#6]
BUG:

When I create a folder or file it does not appear under the history folder. The older version of history items also not working,

Try to test with 2-3 level deep file structure.

**Comment by zabel-xyz** [comment]
You are right, it no longer works with level deep file structure.
I contacted the VSCode team and hope to have something new soon.
(https://github.com/Microsoft/vscode/issues/15424)

**Comment by zabel-xyz** [comment]
The new version (1.1.0) will fix this issue.

**Comment by ligadata-alaa** [comment]
not working on Version 1.14.2

**Comment by zabel-xyz** [comment]
It's work fine. Retry with new version 1.3.0,
If you have still an issue, please open a new issue with more information (system, settings, files structure...)
