### ISSUE TITLE
How does "go to definition" exclude specified directories, such as "./history"?

### ISSUE THREAD

**Issue by waynerQiu** [zabel-xyz/local-history#60]
![image](https://user-images.githubusercontent.com/3021822/49923776-7a761d00-feef-11e8-9ee4-b3f9aa3e476d.png)

**Comment by waynerQiu** [comment]
![image](https://user-images.githubusercontent.com/3021822/49923790-8661df00-feef-11e8-9267-e30e21b10ef2.png)
How does "go to definition" exclude specified directories, such as "./history"?

**Comment by zabel-xyz** [comment]
- Add search exclude in your settings : `"search.exclude": { "**/.history": true },`
  (But this doesn't work with all extensions like php [#40](https://github.com/zabel-xyz/local-history/issues/40))
- Move .history in another specific folder using `local-history.path`
