### ISSUE TITLE
how to apply the history changes

### ISSUE THREAD

**Issue by ctf0** [zabel-xyz/local-history#69]
am not sure if its possible but is there anyway where you can open the history file and apply the changes like git ?

**Comment by zabel-xyz** [comment]
I'm not sure what you want...

For complete replace
There is the item menu "Restore" to replace current file with the history version.
[see menu in tree](https://github.com/zabel-xyz/local-history/blob/master/images/Tree.png)

or Partial 
Compare history and current version. You can copy lines from history to current version in diff editor.

**Comment by ctf0** [comment]
many thanx for the img as eveytime i use restore i was getting an error, so now i actually know how to use it. "maybe remove it from the command panel ?"

but i was talking about the diff tool, is there a way to show the same panel vscode git use above each diff block where u chose to either merge or ignore ?

**Comment by zabel-xyz** [comment]
Sorry, but diff tool is a vscode feature. Contact vscode team if you want some improvement.

**Comment by zabel-xyz** [comment]
If you get an error when you restore, please give me some details to fix this issue

**Comment by ctf0** [comment]
as the restore command is available in the command panel, so using it without having an opened diff view will give an error.

if there is away to only enable it when the diff view is visible it would be very helpful

**Comment by zabel-xyz** [comment]
The command restore is only for the popupmenu in the tree. So, I'll remove it from command panel.

I'll perhaps implement something else when a history file is open or in the diff view, I agree it could be helpful.

**Comment by askhogan** [comment]
@zabel-xyz Thank you for this great tool. As a user, coming from Webstorm, where there was built in local history, this tool feels like home. Thank you for allowing users to save outside the workspace (awesome) and also allowing users to configure options vs being too opinionated about it - been surprised that many vs code extensions do not allow you to configure. 

One tip - hopefully helps others - my diff was not working in VS code until I added the setting below to settings.json

```"diffEditor.renderSideBySide": true```

**Comment by zabel-xyz** [comment]
Thank you for your fix, but I have this isssue in progress and already fix this but not published yet.
Dont't close issues if it is in progress, thank you.
