### ISSUE TITLE
[feature] auto populate undo list using file history 

### ISSUE THREAD

**Issue by ctf0** [zabel-xyz/local-history#70]
so instead of opening the history view of the current file, u simply use `ctrl+z` like usual and the undo list will be auto populated from the history files from the most recent to the oldest.

to avoid heavy operations on vscode, this feature could be activated the moment u start using `ctrl+z` in a file with history.

**Comment by zabel-xyz** [comment]
I don't think I can access to undo list and it's not a good idea to populate this list with the full content of history files...
The only thing I can do is a restore operation, and it's already implemented, You can choose which history file to restore in the tree...

**Comment by ctf0** [comment]
the list wasnt going to have the full content of course, only the diff part sorted from bottom > up.

so you would have the same experience of using undo but slightly more enhanced

**Comment by zabel-xyz** [comment]
The only data that I have is the full content of each file version, not the diff, and a file can have many diff.
It's not like git and the commit system ! So your suggestion is not compatible with the way of this extension is working...
