### ISSUE TITLE
No Historie

### ISSUE THREAD

**Issue by KlausWilly** [zabel-xyz/local-history#74]
Hello 

i am working on windows10 1803
here the importent things:
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Datum: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
Betriebssystem: Windows_NT x64 10.0.17134

As remarked in the comparable issues, i set the following settings
"local-history.dateLocale": "de-DE",
    "local-history.daysLimit": 0,
    "local-history.absolute": false,
    "local-history.enabled": 1,
    "local-history.path": "${workspaceFolder}"

I open only one File change some and save.
nothing happens.

the path ${workspaceFolder}.\history does'nt exist. Is this the problem.
Will the path be created if not existing ?

best wishes 
Klaus

**Comment by zabel-xyz** [comment]
Yes, the path is created via mkdirp before saving history.
What is your workspaceFolder ? Is the file you open in the workspaceFolder path ?

**Comment by KlausWilly** [comment]
I think there is no workspaceFolder, because i open a File anywhere on my PC.
I tought the extension is for having a history for each File i open in VS-code, not just files that are part of a VS-Studio/VS-Code solution.
Am I wrong?

**Comment by zabel-xyz** [comment]
If you want to save all files without a workspaceFolder, you need an external history path 
e.g.: local-history.path: `"%AppData%/Code/User/local-history"` and `absolute: true`

You can use **user** settings for a default folder like this and specify"local-history.path": "${workspaceFolder}" in your **workspace** setting (used only when you work in a folder)...
