### ISSUE TITLE
mkdir exception by long paths

### ISSUE THREAD

**Issue by smasala** [zabel-xyz/local-history#75]
When the path to the history file is too long (windows 10) then the following exception occurs:

```
Error with mkdir: 'RangeError: Maximum call stack size exceeded' file
```

**Comment by zabel-xyz** [comment]
I'll use the original node function fs.mkdir(path[, options], callback).
Now it's available with option recursive. I hope this would fix this issue...

**Comment by smasala** [comment]
Thanks :+1

**Comment by zabel-xyz** [comment]
Try with version 1.8.0
