### ISSUE TITLE
is it possible to follow file rename

### ISSUE THREAD

**Issue by ctf0** [zabel-xyz/local-history#78]
atm when the file gets renamed, all the prev history is not longer available.
so is there a way for the plugin to keep file name history in each file "maybe as a comment"  when it gets renamed ?

**Comment by zabel-xyz** [comment]
There isn't such a feature.
The goal wasn't to replace someting like git, but to keep a local and temporary trace of saving files when a problem or accident occured. 
So I'll not implement something like this...

**Comment by ctf0** [comment]
its not git replacement, it simply a way to have a persistent history of a renamed file.
