### ISSUE TITLE
local-history.path dont work in UserSettings

### ISSUE THREAD

**Issue by BarneyG77** [zabel-xyz/local-history#8]
I have installed the Extension and for Folders the Setting local-history.path work fine. I also made the entry in UserSettings so that every file i modifed will have a backup. But this Setting will be ignored. Can you please fix this?

**Comment by zabel-xyz** [comment]
Currently this extension work only if you open a folder, cause the workspace is used to build the structure
e.g.: local-history.path/.history/workspace-folder/[other-subFolders]/fileToSave

I can extend it when a only a file is open, but what structure to implement, an absolute path ? 
e.g.: local-history.path/.history/absolute-path/fileToSave
Does that work for you ?

**Comment by BarneyG77** [comment]
Hi and thanks for your answer.
Yes, that would work for me. I only want a backup for some single files which i often modify. My Default-Editor was UltraEdit and this Editor has a Option to set a Directory where every file will be saved into when the file is modified

**Comment by zabel-xyz** [comment]
Fix in version 1.3.0
