### ISSUE TITLE
History location issue on Ubuntu

### ISSUE THREAD

**Issue by Moghul** [zabel-xyz/local-history#80]
Hi, I'm probably doing something wrong, but I can't figure out how to get this to work the way I want it to.

I'm on Ubuntu, latest version of VS Code, and I'm trying to have the history save in a directory outside of my workspace/git repository. I don't want to modify gitignore instead because I'm the only one using this setup.

My settings are 

```
    "local-history.path": "Documents/CodeHistory",
    "local-history.absolute": true
```

The location of the history that I'm trying to get is ```~/Documents/CodeHistory```.
If I remove those settings, the plugin does save history in the repository, so it does work.

With those settings, nothing happens. No .history is created, no errors are thrown, nothing.

You might ask why I'm using Documents/CodeHistory as the path. When I tried ```~/Documents/CodeHistory```, it created a ```~``` directory in my home directory so I thought it must be able to find the existing Documents/CodeHistory directory.

What are the correct settings for what I'm trying to do?

**Comment by zabel-xyz** [comment]
Hello,
A known issue is that character ~ is not supported yet (see #47)

You can try to use /home/\<user> instead ~ like explain here #43 
(I don't know very well linux...)

In the next version 1.8.0, I'll support the character ~, I have already prepared it (see branch next) but I am too busy right now to test and publish something...

**Comment by zabel-xyz** [comment]
Hello,
A known issue is that character ~ is not supported yet (see #47)

You can try to use /home/\<user> instead ~ like explain here #43 
(I don't know very well linux...)

In the next version 1.8.0, I'll support the character ~, I have already prepared it (see branch next) but I am too busy right now to test and publish something...

**Comment by Moghul** [comment]
Hey, that worked!
