### ISSUE TITLE
```json  { 	"messages": [], 	"activationTimes": { 		"startup": true, 		"codeLoadingTime": 59181, 		"activateCallTime": 2, 		"activateResolvedTime": 5, 		"activationEvent": "*" 	}, 	"runtimeErrors": [] } ```Extension issue

### ISSUE THREAD

**Issue by vidhyesh** [zabel-xyz/local-history#82]
- Issue Type: `Bug`
- Extension Name: `local-history`
- Extension Version: `1.7.0`
- OS Version: `Darwin x64 16.7.0`
- VSCode version: `1.36.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by zabel-xyz** [comment]
What ?! What is your problem ?
