### ISSUE TITLE
Tree is filled only within 1st window instance

### ISSUE THREAD

**Issue by ghost** [zabel-xyz/local-history#88]
I have noticed the side bar populates with history files only for the 1st window instance. Subsequent ones are blank for the same file.

![image](https://user-images.githubusercontent.com/8683446/68887054-8527cc00-06d5-11ea-95de-d17e3b5af46d.png)

![image](https://user-images.githubusercontent.com/8683446/68887082-91ac2480-06d5-11ea-9546-3af26d2ba37b.png)

Version 1.7.0

OS: Win10 Enterprise 64bit

Here are my settings:
```

   "local-history.daysLimit": 0,
   "local-history.maxDisplay": 100,
   "local-history.path": "U:/vscodeBKP/",
   "local-history.treeLocation": "localHistory",
   "local-history.absolute": true,
   "local-history.enable": 1,

```

**Comment by zabel-xyz** [comment]
Hello, 
I tried, but I cannot reproduce
![Multi-windows](https://user-images.githubusercontent.com/16486407/69039675-aa298100-09ec-11ea-9ed7-aa4573b969cf.gif)
How do you open the second window ?
