### ISSUE TITLE
local history stopped working with vscode 1.40.1

### ISSUE THREAD

**Issue by ebadta81** [zabel-xyz/local-history#89]
Hello,

I have default settings, and I realized I have no new versions. I think it is because of the vscode upgrade.

I am using ubuntu.

This is my full settings.json file content:

```json
{
    "C_Cpp.default.compileCommands": null,
    "explorer.confirmDelete": false,
    "editor.minimap.enabled": false,
    "mssql.intelliSense.enableIntelliSense": false,
    "editor.formatOnPaste": false,
    "editor.insertSpaces": false,
    "window.zoomLevel": 0,
    "git.enableSmartCommit": true,
    "editor.autoClosingBrackets": "languageDefined",
    "editor.autoClosingQuotes": "languageDefined",
    "C_Cpp.default.cStandard": "c11",
    "C_Cpp.default.intelliSenseMode": "gcc-x64",
    "code-runner.clearPreviousOutput": true,
    "breadcrumbs.enabled": false,
    "editor.renderControlCharacters": true,
    "editor.renderWhitespace": "none",
    "workbench.tree.indent": 18,
    "explorer.confirmDragAndDrop": false,
    "javascript.updateImportsOnFileMove.enabled": "never",
    "javascript.referencesCodeLens.enabled": true,
    "gitlens.defaultDateFormat": "YYYY-MM-DD HH:mm:ss",
    "gitlens.defaultDateShortFormat": "YYYY-MM-DD",
    "gitlens.currentLine.enabled": false,
    "gitlens.hovers.currentLine.over": "line",
    "gitlens.blame.heatmap.enabled": false,
    "gitlens.hovers.currentLine.enabled": false,
    "files.exclude": {
        "**/.history": true,
        "**/node_modules": true
    },
    "typescript.referencesCodeLens.enabled": true,
    "typescript.implementationsCodeLens.enabled": true,
    "typescript.updateImportsOnFileMove.enabled": "always",
    "terminal.integrated.shell.linux": "/bin/bash"
}
```

What other information do you need for error tracking?

**Comment by zabel-xyz** [comment]
Hello,
It works fine for me...
What do you open a single folder, multi-folders, a single file...

**Comment by ebadta81** [comment]
It's a normal project. I open a folder.

**Comment by shai** [comment]
I'm using the same version and it doesn't work for me either. I just started using the extension, but it just doesn't work from the get-go.

**Comment by vibl** [comment]
Stopped working for me too.

I lost a few weeks of work history...

**Comment by vibl** [comment]
@zabel-xyz, feel free to ask for specific infos.

**Comment by zabel-xyz** [comment]
Sorry to see that a lot of people face this issue
I tested without any problem
- on windows 10 platform
- within virtual machine on ubuntu 16.04 

So, I need some help. Someone who encounter this problem must debug this extension and find out what goes wrong... 
Perhaps VS Code changed something in last release, but I don't know what....

**Comment by ebadta81** [comment]
My OS is Ubuntu 18.04 with last updates. Maybe this is the difference.

**Comment by vibl** [comment]
Ubuntu 19.04 here.

**Comment by MarekLew** [comment]
#90 :) Global setting is not ignored when setting.json is open in tab. LOL

**Comment by ebadta81** [comment]
now with vscode auto update it is working again

**Comment by vibl** [comment]
It still doesn't work for me.

I've tried reinstalling and removing .history

Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T15:04:31.999Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.0.0-38-generic

**Comment by alexdx0** [comment]
Extension do not work.
VSCode:
Version: 1.42.0 (user setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:34.058Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 6.3.9600

On React JS files

**Comment by danchann** [comment]
Extension missing from Explorer panel.
Version: 1.42.0 (system setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:34.058Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17134

**Comment by zabel-xyz** [comment]
see issues #98

**Comment by witcradg** [comment]
I had this problem. I fixed it by uninstalling THEN EXIT VsCode. Restart VsCode then reinstall.
Lost a lot of history in multiple projects.
