### ISSUE TITLE
add started version file

### ISSUE THREAD

**Issue by MarekLew** [zabel-xyz/local-history#9]
Please add option to save original/started version file before is changed.

example (first save):

- `.history/foo/bar/myFile_00000000000000.ts` -- origin file
- `.history/foo/bar/myFile_20151212205930.ts` -- modify history

if `.history/foo/bar/myFile_00000000000000.ts` exist then not modified.

**Comment by zabel-xyz** [comment]
I have already noticed that the original version of the file is lost.
I don't think I'll implement an option for this.
But your idea to name the file myFile_00000000000000.ts is good, so I'll implement something like this.

**Comment by MarekLew** [comment]
In this moment I tested my solution.

**Comment by MarekLew** [comment]
It is not finish jet, https://github.com/MarekLew/local-history/commit/d98655c367bbcbaea34730692d594ba6b0d8b95e
