### ISSUE TITLE
can be save only file name with out date

### ISSUE THREAD

**Issue by engacs** [zabel-xyz/local-history#92]
Hi, how its posibly to save log history with eveything file change save file name only example
now its save like .history/foo/bar/myFile_20151212205930.ts
so i need its like .history/foo/bar/myFile.ts

only save the last of change
so how its posibly

**Comment by zabel-xyz** [comment]
It's not possible., save always with date.

**Comment by engacs** [comment]
so i am Developer can tell me which file has be save if posibly to editor that code file becouse i am very importance to save last editer becouse i need to make a  version  folders our system

**Comment by engacs** [comment]
Thanks i solving that i can edit the file 

history.controller.ts
nowInfo =  '' ;  //   nowInfo = now.toISOString().substring(0, 19).replace(/[-:T]/g, '');
const revisionFile = this.joinPath(settings.historyPath, revisionDir, p.name, p.ext, `${nowInfo}`);

**Comment by zabel-xyz** [comment]
Yes, this is a good beginning to save file, but all features are not supported.
e.g.:
```
private internalDecodeFile(filePath: string, settings: IHistorySettings, history?: boolean): IHistoryFileProperties {
[ ... ]    
        let index = p.name.match(me.regExp);
            if (index) {
                date = new Date(index[1],index[2]-1,index[3],index[4],index[5],index[6]);
                p.name = p.name.substring(0, index.index);
            } else
                return null; // file in history with bad pattern !
        }
```
