### ISSUE TITLE
[feature] dont create a new revision if current document data is not different from the last revision

### ISSUE THREAD

**Issue by ctf0** [zabel-xyz/local-history#93]
atm even if the file have no difference between it and the last time it was saved, the ext still create a new revision, which create unnecessary noise in the history list.

**Comment by robgrace** [comment]
seeing this too, on Mac.  I save a file, and immediately it is marked dirty (modified) again even though the content didn't change

**Comment by ctf0** [comment]
https://marketplace.visualstudio.com/items?itemName=ctf0.local-history-new
