### ISSUE TITLE
"local-history.treeLocation": "explorer" seems not to work anymore

### ISSUE THREAD

**Issue by dominikzogg** [zabel-xyz/local-history#98]
In my understanding, this option allows me to see local history in explorer view instead of a separate pane (via icon). If thats the case its not working.

Version: 1.7.0

**Comment by noisnemid** [comment]
yes! suddenly not work after vscode upgraded to 1.42.0

**Comment by zabel-xyz** [comment]
I confirm it doesn't work anymore since 1.42.0.
I'll see what changed...

**Comment by zabel-xyz** [comment]
Fix in version 1.8.0

**Comment by noisnemid** [comment]
Marvelous!!!
Thank you!!!

**Comment by gtranter** [comment]
I am using VS Code 1.42.1 and local-history 1.8.0 and I do not see the local history in the tree view. Has 1.42.1 broken this again?

**Comment by levydev** [comment]
Still broken for me despite having the latest vsc and lh versions
