### ISSUE TITLE
Do not work with 1.42.0

### ISSUE THREAD

**Issue by alexdx0** [zabel-xyz/local-history#99]
Extension do not work.
VSCode:
Version: 1.42.0 (user setup)
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:34.058Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 6.3.9600

On React JS files

**Comment by noisnemid** [comment]
it's in the active bar now , but not showed in explorer part, while the author confirmed this as a bug,

**Comment by zabel-xyz** [comment]
What doesn't work ? 
Like @noisnemid said, the treeview is in only in the active bar since 1.42.0. see #98 
If it's this issue, you can close this one, otherwise I need more informations....

**Comment by alexdx0** [comment]
> What doesn't work ?
> Like @noisnemid said, the treeview is in only in the active bar since 1.42.0. see #98
> If it's this issue, you can close this one, otherwise I need more informations....

Indeed, it works in the active bar. I didn’t see right away. This is enough for now. But it would be nice to return to explorer. I hope you fix this bug. Thanks.
![Screenshot_20](https://user-images.githubusercontent.com/33890200/74505283-cf545f80-4f07-11ea-8aa3-b53162374769.png)
